services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    network_mode: host
    command: anvil -a 0.0.0.0 -p 8545
    environment:
      - ANVIL_IP_ADDR=0.0.0.0

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - shared-data:/shared
    environment:
      - ETH_RPC_URL=http://127.0.0.1:8545
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    depends_on:
      - anvil

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
    network_mode: host
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    network_mode: host
    volumes:
      - shared-data:/shared
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - ETH_RPC_URL=http://127.0.0.1:8545
      - DASHBOARD_URL=http://127.0.0.1:3002
    depends_on:
      - anvil

volumes:
  shared-data:
